apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: openshift-intern-workshop-akhil
  name: openshift-intern-workshop-akhil
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-intern-workshop:latest
  source:
    git:
      uri: https://github.com/akhil-rane/openshift-intern-workshop
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python-36:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: R0_vqLZduOGcAhCetEuJ
    type: GitHub
  - generic:
      secret: BrRXVtr3ojJkX6_VGzLD
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
